### ISSUE TITLE
Inconsistent client performance

### ISSUE THREAD

**Issue by sennpang** [BitPhinix/slate-yjs#322] opened 2022-02-16 09:30 UTC
https://user-images.githubusercontent.com/16861647/154235229-6eb863bb-adc2-4d42-a308-4894455311cf.mov

**Comment by BitPhinix** [comment] 2022-02-16 09:44
https://github.com/udecode/plate/issues/1380 is also caused by this

**Comment by BitPhinix** [comment] 2022-03-06 14:41
Fixed in the latest release, core now also has a way more robust test suite so something like this shouldn't happen again 🙏

**Closed by BitPhinix** 2022-03-06 14:41 UTC
Labels: bug

**Comment by trannhutle** [comment] 2022-10-13 10:11
Hello @sennpang,
Would you mind showing me how to integrate Plate with slate-yjs ?
i really appreciate it. Thank you!

**Comment by sennpang** [comment] 2022-10-14 04:13
Sorry, i just run the demo and find that bug
this maybe will help you 
[https://docs.slate-yjs.dev/walkthroughs/collaboration-hocuspocus](https://docs.slate-yjs.dev/walkthroughs/collaboration-hocuspocus)
[https://docs.yjs.dev/ecosystem/connection-provider](https://docs.yjs.dev/ecosystem/connection-provider)
